## DarthCraft Auto Location Plugin Configuration File.

## Australia 
AU:
    X: 55
    Y: 67
    Z: 33
## Belgium     
BE:
    X: 55
    Y: 67
    Z: 33
## Canada
CA:
    X: 55
    Y: 67
    Z: 33
## Denmark
DK:
    X: 55
    Y: 67
    Z: 33
## France
FR:
    X: 55
    Y: 67
    Z: 33 
## Germany
GE:
    X: 55
    Y: 67
    Z: 33  
## Greece
GR:
    X: 55
    Y: 67
    Z: 33 
## Ireland
IE:
    X: 55
    Y: 67
    Z: 33  
## Netherlands
NL:
    X: 55
    Y: 67
    Z: 33  
## New Zealand
NZ:
    X: 55
    Y: 67
    Z: 33 
## United Kingdom of Great Britain and Northern Ireland
GB:
    X: 55
    Y: 67
    Z: 33  
#United States of America
US:
    X: 23
    Y: 23
    Z: 23  
# Others
OTHER:
    X: 55
    Y: 55
    Z: 55
---
